version: '3.8'

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: php_base
            args:
                REMOTE_HOST: 'host.docker.internal'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - '8080:80'
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
            target: node_deps
        restart: unless-stopped
        tty: true
        ports:
            - '${VITE_PORT:-5173}:5173'
        working_dir: /var/www
        volumes:
            - .:/var/www
